[server]
port = "8080"
shutdown-port = "8005"
redirect-port = "8443"

# Configuration for the AJP connector
#enable-ajp-connector = "true"   # comment out line to disable AJP port
ajp-port = "8009"

[userdbrealm]
roles = ["sysadmin", "deployer", "auditor"]

[[userdbrealm.users]]
username = "admin"
password = "password"
roles = "manager-gui,manager-script,manager-jmx,manager-status" 

[[userdbrealm.users]]
username = "bmeyer"
password = "habitat"
roles = "manager-gui"

[host]

[host.localhost]
unpack-wars = "true"
auto-deploy = "true"

[host-manager]
#localhost-only = "true" # comment out line to enable access from all